services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password  # Устанавливаем пароль для root
      PGDATA: /data/mysql
    volumes:
      - mysql:/data/mysql
    ports:
      - "3307:3306"
    networks:
      - mysql  # Указываем сеть mysql
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  mysql:  # Добавляем определение сети mysql
    driver: bridge
  postgres:
    driver: bridge

volumes:
  mysql:  # Определение тома для mysql
  pgadmin:
